### ISSUE TITLE
Azure-devops readme - Missing step to install Azure devops extension to az cli for the current steps to work

### ISSUE THREAD

**Issue by jananivMS** [microsoft/cobalt#102]
1. In addition to installing Azure CLI, the Azure devops extension should be installed for the "az devops" command in the readme to work. 

The below link can be used in the readme for how to install the devops extension.

https://marketplace.visualstudio.com/items?itemName=ms-vsts.cli

2. The command that is in the readme currently is "az devops project create -n $PROJECT_NAME".

This command is incorrect and has to be like the below instead.

"az devops project create --name $PROJECT_NAME --organization $ORG_NAME"

where PROJECT_NAME --> name to give to your project
ORG_NAME --> URI of your devops organization eg. http://dev.azure.com/epicstuff

**Comment by nmiodice** [comment]
We believe this to be well documented now.
