### ISSUE TITLE
Purchase SSL Certificate

### ISSUE THREAD

**Issue by erikschlegel** [microsoft/cobalt#154]
### Description
*As a technical operator, I'd like to use a secure and registered SSL certificate when deploying the azure simple template to a target azure subscription. 

### Acceptance Criteria
- [ ] Should purchase a new SSL certificate.
- [ ] Should have the private and public certificate key's stored in Azure Keyvault
- [ ] The public and private SSL certificates should be configured and imported to app gateway for azure simple deployments.
- [ ] Should provide screen shots of the azure keyvault entries for the certificate.

**Comment by iphilpot** [comment]
Just seeing this. Can we move this to Sprint 8? Let's Encrypt provides a free service that is pretty standard. We should discuss options... https://letsencrypt.org/docs/client-options/

**Comment by erikschlegel** [comment]
> @erikschlegel Just seeing this. Can we move this to Sprint 8? Let's Encrypt provides a free service that is pretty standard. We should discuss options... https://letsencrypt.org/docs/client-options/

Sure thing. This isn't as urgent considering that we're building on top of existing partner infrastructure leveraging existing certs.
