### ISSUE TITLE
App Service Terraform Module Improperly Formatted

### ISSUE THREAD

**Issue by ericpera-msft** [microsoft/cobalt#170]
When I try to execute `Terraform Plan` against the App Service Terraform module located at "infra/modules/providers/azure/app-service/", I encounter a syntax error stating 
```
Error: Unsupported block type

  on main.tf line 10, in resource "azurerm_app_service" "appsvc":
  10:   app_settings {

Blocks of type "app_settings" are not expected here. Did you mean to define
argument "app_settings"? If so, use the equals sign to assign it a value.
```

To remedy this, the line `app_settings {` should be changed to `app_settings = {`

**Comment by nmiodice** [comment]
@ericpera-msft can you verify what version of terraform you are using?

This change is a part of the TF 12 upgrade (https://github.com/microsoft/cobalt/pull/172/files) but it has not been giving us issues in TF 11 so far.

**Comment by ericpera-msft** [comment]
@nmiodice I am using Terraform v0.12.1 so you are spot on about that. I'll close this issue.
