### ISSUE TITLE
Implement AuthN via App Service Module

### ISSUE THREAD

**Issue by TechnicallyWilliams** [microsoft/cobalt#201]
### Description
As a developer, I'd like to enable EasyAuth on my App Service, so that I can authenticate users.

### Acceptance Criteria
- [x] Should configure EasyAuth using `auth_settings` code block in TF docs in existing App Service Module
- [x] Should use AAD Application ID in `auth_settings` code block 

Also, here are a few points that need to be addressed:

1. Current App Service Module will need to be changed to support `auth_settings`
1. We're only focusing on Web Applications not native applications for the AAD Application type.
1. This user story does not include creating AAD Application through Service Principal module. Instead, it includes using an existing AAD Application from a different tenant.
1. App Service Authentication registration should key off of enabling multi-tenant.

### Resources
[Technical Design Doc](https://github.com/microsoft/cobalt/blob/master/design-reference/architecture/authn/providers/azuread/easyauth.md)
[Terraform App Service Auth Docs](https://www.terraform.io/docs/providers/azurerm/r/app_service.html#auth_settings)
[Terraform AzureAD App Docs](https://www.terraform.io/docs/providers/azuread/r/application.html)

#### App Service Module
1. Create `auth_settings` code block that contains `active_directory` code block.
2. Test deployment with an existing AAD application ID from a different tenant. Templatize the tenant GUID and client id.
3. Update all references to app-service-name in main project due to type change from map to nested map.
4. Update all references to app-service-name in testing suite due to type change from map to nested map.

#### Integration Test
1. Test by using a "throw away" Template that creates an AAD Application and then references this to configure Easy Auth in App Service. Verify in the portal.
    1. Doesn't need to be in an existing template... Just create a template to test and take a screenshot.

**Comment by erikschlegel** [comment]
@TechnicallyWilliams please add the t-shirt sized estimation label for this user story.
