### ISSUE TITLE
[ ASE ] Investigate sourcing docker username/password used for WebApp CD from KeyVault

### ISSUE THREAD

**Issue by nmiodice** [microsoft/cobalt#206]
### Description
*As a developer, I'd like to not have credentials for my ACR visible in the Azure Portal. Instead I'd like to source them from KeyVault so that I don't leak secrets*

### Acceptance Criteria
Reference: [Done-Done Checklist] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/DoneDone.md)
- [x] Determine if sourcing the secrets from KeyVault is possible
- [ ] If it is possible, write implementation story

### Resources
[Relevant Documentation](https://docs.microsoft.com/en-us/azure/app-service/app-service-key-vault-references#source-application-settings-from-key-vault)

### Tasks
*Stories are intended to be completed in a single sprint; if task breakdown creates addition work then team should discuss promoting the Story to an Epic.
Reference: [Minimal Valuable Slices] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/MinimalSlices.md)*

Reference: [How to Write Better Tasks] (http://agilebutpragmatic.blogspot.com/2012/04/splitting-story-into-tasks-how-to-write.html)

**_Assignee should break down work into tasks here_**

**Comment by iphilpot** [comment]
Using key vault to store the secrets for ACR Service Principle works. Calling this done...
