### ISSUE TITLE
Implement AuthN unit testing

### ISSUE THREAD

**Issue by TechnicallyWilliams** [microsoft/cobalt#214]
### Description
As a contributor, I'd like unit testing for authN to be in place in order to facilitate my understanding of authN in Cobalt and to also serve as a model for authN logic of concern.

### Acceptance Criteria
- [ ] Unit tests should assert that the default tenant_id is used within the terraform plan when an external_tenant_id isn't provided.
- [ ] Unit tests assert that "AzureActiveDirectory" is the default authentication issuer provider.

### Resources
[Original issue](https://github.com/microsoft/cobalt/issues/201)

#### App Service AuthN Tests
1. Add "AzureActiveDirectory" as an assertion to the currently existing unit tests for all templates.
2. Build a function in go that asserts tenant_id based on tenant_id settings.

**Comment by iphilpot** [comment]
This should be completed as part of the AuthN stories acceptance criteria.
