### ISSUE TITLE
[ ASE ] Implement: Delete locks on Azure Resources to prevent outages

### ISSUE THREAD

**Issue by nmiodice** [microsoft/cobalt#216]
### Description
*As a template maintainer I want to build a template that prevents accidental resource deletion so that I don't cause a service outage accidentally.*

Design: https://github.com/microsoft/cobalt/issues/208

### Acceptance Criteria
Reference: [Done-Done Checklist] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/DoneDone.md)
- [ ] Implement design from https://github.com/microsoft/cobalt/issues/208

### Resources
Design: https://github.com/microsoft/cobalt/issues/208

### Tasks
*Stories are intended to be completed in a single sprint; if task breakdown creates addition work then team should discuss promoting the Story to an Epic.
Reference: [Minimal Valuable Slices] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/MinimalSlices.md)*

Reference: [How to Write Better Tasks] (http://agilebutpragmatic.blogspot.com/2012/04/splitting-story-into-tasks-how-to-write.html)

**_Assignee should break down work into tasks here_**

**Comment by erikschlegel** [comment]
Addressed in PR #226
