### ISSUE TITLE
Test Bug: Isolated Service template will fail if the "name" variable is updated

### ISSUE THREAD

**Issue by awkwardindustries** [microsoft/cobalt#248]
### Description
When testing the Isolated Service Single Region template, we modified the `infra/templates/az-isolated-service-single-region/terraform.tfvars` "name" value. This caused the `unit_test.go` tests to fail because they are hard-coded to expect the original "isolated-service" name value.

### Acceptance Criteria
Reference: [Done-Done Checklist] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/DoneDone.md)
- [x] Should be able to change the Isolated Service terraform.tfvars name value without breaking unit tests

### Resources
* Related to #254

### Tasks
*Stories are intended to be completed in a single sprint; if task breakdown creates addition work then team should discuss promoting the Story to an Epic.
Reference: [Minimal Valuable Slices] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/MinimalSlices.md)*

Reference: [How to Write Better Tasks] (http://agilebutpragmatic.blogspot.com/2012/04/splitting-story-into-tasks-how-to-write.html)

**_Assignee should break down work into tasks here_**

**Comment by KeithJRome** [comment]
Resolved as a part of larger work item #254
