### ISSUE TITLE
[ASE] Inconsistent App Service Key vault Access Policy

### ISSUE THREAD

**Issue by TechnicallyWilliams** [microsoft/cobalt#294]
### Background

The current chain of events involves an App Service listening to a webhook so that the App Service can pull an image from ACR using it's keyvault credentials and keyvault access policy. However, keyvault access policy settings get removed on subsequent deployments. 

### Description
*As a user, I'd like my keyvault access policies to be resilient to subsequent deployments so that I can have confidence that acr image pulls won't break in an unexpected way.

### Acceptance Criteria
Reference: [Done-Done Checklist] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/DoneDone.md)
- [x] Key vault access policy sticks around for subsequent deployments

Also, here are a few points that need to be addressed:

1. Access policies are inconsistent for get/list operations. Subsequent deployments remove them.
1. Althought subsequent deployments remove them, the application container still runs. This potentially means that the access policies are not needed or are cached in some way.
1. Keyvault access policy submenu UI has a bug. Hit the refresh button for a reflection current keyvault access policuy state

### Resources

- Existing Keyvault access policy: 
![image](https://user-images.githubusercontent.com/10041279/64820703-8d994480-d576-11e9-9592-b273e6b9b1cf.png)

- Non-existing keyvault access policy: 
![image](https://user-images.githubusercontent.com/10041279/64820760-af92c700-d576-11e9-8685-31b1268aa313.png)

### Tasks
*Stories are intended to be completed in a single sprint; if task breakdown creates addition work then team should discuss promoting the Story to an Epic.
Reference: [Minimal Valuable Slices] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/MinimalSlices.md)*

Reference: [How to Write Better Tasks] (http://agilebutpragmatic.blogspot.com/2012/04/splitting-story-into-tasks-how-to-write.html)

**_Assignee should break down work into tasks here_**
1. Investigate what's causing Inconsistent App Service key vault access policies

**Comment by KeithJRome** [comment]
This appears to possibly be a glitch in the portal. The Access Policies disappear from the keyvault for a short period of time once the deployment begins updating it. However they seem to reappear a short time later (refreshing the view does not help).

**Comment by KeithJRome** [comment]
I suggest downgrading this one to `wontfix` or `on hold` until/unless it resurfaces as a verified problem as opposed to a benign UI glitch. @James-Nance @TechnicallyWilliams @iphilpot
