### ISSUE TITLE
Web hook should be specific to a deployment target, not all deployment targets

### ISSUE THREAD

**Issue by TechnicallyWilliams** [microsoft/cobalt#299]
### Background

A web hook should be specific to an application. Instead, when a webhook is triggered, all applications re-pull their respective image.

### Description
As a user, I'd like an image push to ACR to only deploy and impact the application that it's intended for.

### Acceptance Criteria
Reference: [Done-Done Checklist] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/DoneDone.md)
- [ ] Logs shows that an image push only triggers one webhook among a list of them.

### Resources
*Technical Design Document*
*Mockups*

### Tasks
*Stories are intended to be completed in a single sprint; if task breakdown creates addition work then team should discuss promoting the Story to an Epic.
Reference: [Minimal Valuable Slices] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/MinimalSlices.md)*

Reference: [How to Write Better Tasks] (http://agilebutpragmatic.blogspot.com/2012/04/splitting-story-into-tasks-how-to-write.html)

**_Assignee should break down work into tasks here_**
- Investigate the relationship a web hook has with other web hooks

**Comment by nmiodice** [comment]
This will be no longer valid as a result of https://github.com/microsoft/cobalt/issues/316. Will close
