### ISSUE TITLE
404 hyperlink in Infrastructure deployment into Azure via Azure DevOps documentation

### ISSUE THREAD

**Issue by helayoty** [microsoft/cobalt#384]
**Current behavior**
The link for "[Getting Started - Advocated Pattern Owner]"(https://github.com/microsoft/cobalt/blob/master/devops/providers/GETTING_STARTED_ADD_PAT_OWNER.md)" is not working 

**Expected behavior**

The link should display the right page

**Steps to reproduce the issue**

- Go to https://github.com/microsoft/cobalt/tree/master/devops/providers/azure-devops#step-1-account-setup
- Try to click the hyperlink in the first step "Getting Started - Advocated Pattern Owner "
- Page opens with a 404 status

**Comment by helayoty** [comment]
Cc: @nmiodice

**Comment by helayoty** [comment]
More 404 hyperlinks found [here](https://github.com/microsoft/cobalt/blob/master/docs/GETTING_STARTED_COBALT_DEV.md#deploying-your-first-template) as well

**Comment by nmiodice** [comment]
PR: https://github.com/microsoft/cobalt/pull/385

**Comment by nmiodice** [comment]
PR merged
