### ISSUE TITLE
Insufficient arguments for HttpGet in Service Endpoint validation in Cosmosdb 

### ISSUE THREAD

**Issue by mahhanifi** [microsoft/cobalt#403]
### Description
As a user, I'd like to be able to test the service endpoint so that I can validate the service response. 

### Acceptance Criteria
- [This line](https://github.com/microsoft/cobalt/blob/master/infra/modules/providers/azure/cosmosdb/tests/integration/cosmos.go#L55) needs to have the proper number of arguments for `HttpGet` method.

### Resources
Here is the current error on the mentioned line:

``` 
too few arguments in call to httpClient.HttpGet
```

**Comment by nmiodice** [comment]
This has been resolved
