### ISSUE TITLE
Define folder structure.

### ISSUE THREAD

**Issue by rickrain** [Microsoft/cobalt#44]
Guidance is needed on the folder structure and location for terraform modules, scripts, and other artifacts used to deploy the solution.

**Comment by rickrain** [comment]
There is a proposed folder structure defined [here](https://github.com/Microsoft/entref-appservice-containers/wiki/td-devops-infrax-templates) that I like.

**Comment by James-Nance** [comment]
This issue is now a dupe - closing.
