### ISSUE TITLE
Application Insights preconfigured module

### ISSUE THREAD

**Issue by James-Nance** [microsoft/cobalt#87]
### Description
*As a developer, I can deploy Application Insights to ingest and view telemetry and logged data from  App Services .*

### Acceptance Criteria
Reference: [Done-Done Checklist] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/DoneDone.md)
- [ ] Should ‹testable condition that should be satisfied›
- [ ] Should ‹testable condition that should be satisfied›
- [ ] …

Also, here are a few points that need to be addressed:

1. Constraint 1;
1. Constraint 2;
1. Constraint 3.

### Resources
*Technical Design Document*
*Mockups*

### Tasks
*Stories are intended to be completed in a single sprint; if task breakdown creates addition work then team should discuss promoting the Story to an Epic.
Reference: [Minimal Valuable Slices] (https://github.com/Microsoft/code-with-engineering-playbook/blob/master/Engineering/BestPractices/MinimalSlices.md)*

Reference: [How to Write Better Tasks] (http://agilebutpragmatic.blogspot.com/2012/04/splitting-story-into-tasks-how-to-write.html)

**_Assignee should break down work into tasks here_**

**Comment by TechnicallyWilliams** [comment]
#### User Story Rough Draft

![image](https://user-images.githubusercontent.com/10041279/57706034-990d4b00-762a-11e9-9015-fd452f8a4425.png)
