### ISSUE TITLE
YAML file missing in instructions to set up CI/CD on Azure DevOps

### ISSUE THREAD

**Issue by melonrush13** [microsoft/cobalt#92]
YAML file is missing in [these](https://github.com/microsoft/cobalt/blob/master/devops/providers/azure-devops/README.md) instructions in step 3 to set up CI/CD with Azure DevOps. 

Link is broken and leads to a 404. [Here](https://github.com/microsoft/cobalt/blob/master/devops/providers/azure-devops/azure-pipelines.yml) is the link to the 404.

**Comment by erikschlegel** [comment]
This will be covered in the infrastructure CI/CD implementation user story.
