### ISSUE TITLE
Backend Setup Template Link Broken 

### ISSUE THREAD

**Issue by melonrush13** [microsoft/cobalt#97]
When following the instructions to set up your local environment (Step 4 in documentation [here](https://github.com/microsoft/cobalt) ), we are brought to this [page](https://github.com/microsoft/cobalt/blob/master/test-harness/README.md). Under the prerequisites bullet-list, it reads 'You can use our backend state **setup template** to provision the storage resources.' 

When the user clicks on the **setup template** link [here](https://github.com/microsoft/cobalt/blob/master/test-harness/(/infra/templates/backend-state-setup/README.md)), it leads us to a 404 error.

**Comment by nmiodice** [comment]
Will be covered in https://github.com/microsoft/cobalt/issues/241 since we need to re-write the document. Closing in favor of https://github.com/microsoft/cobalt/issues/241
